codecov:
  require_ci_to_pass: true
  
  notify:
    # For Discord notifications, use GitHub Actions instead (see workflow file)
    # Codecov's webhook system has limited Discord support
    webhook:
      default:
        url: "https://discordapp.com/api/webhooks/1442473342350131201/p8xIERb0zaaDpVk1cykZCnHWdvjtaOdHxuk3qzpnFDL8rKg2_CxJtq0R4Ok32L1KTQYg"
        only_pulls: false

# Coverage thresholds - don't fail PR if coverage decreases slightly
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 20%  # Allow up to 20% coverage decrease
    patch:
      default:
        target: 70%  # New code should have 70% coverage
        threshold: 10%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false